### ISSUE TITLE
AttributeError: module 'polling' has no attribute 'poll'

### ISSUE THREAD

**Issue by achin16** [justiniso/polling#27]
Hello Team,

I am trying to run py script from my local and am seeing the below error. Can someone help on this? 

```
python3 polling.py xxxxxxxxxx setup-node-v3.3.0-375
Traceback (most recent call last):
  File "polling.py", line 10, in http_poll
    polling.poll(
AttributeError: module 'polling' has no attribute 'poll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "polling.py", line 55, in <module>
    http_poll()
  File "polling.py", line 17, in http_poll
    except polling.TimeoutException as e:
AttributeError: module 'polling' has no attribute 'TimeoutException'
```

py script:

```
import requests
import polling
import json
import os
import sys

def http_poll():
    try:
        requestURL = 'https://api.github.com/xxxxxxx'
        polling.poll(
            lambda: requests.get(
                requestURL, headers).content,
            step=60,
            max_tries=10,
            check_success=check_issue_name
        )
    except polling.TimeoutException as e:
        print(e.__cause__)

def check_issue_name(response):
    issue_array = json.loads(response)
    issue_list = []

    for item in issue_array:
        issue_details = {"title": None, "number": None}
        issue_details['title'] = item['title']
        issue_details['number'] = item['number']
        issue_list.append(issue_details)

    if issue_list is not None:
        for obj in issue_list:
            if obj['title'] == get_issue_title():
                print("Debug Issue Title:", obj['title'])
                print("Debug Issue Id:", obj['number'])
                numToEnvVariables(obj['number'])
                return True
    return False


# Read and store value as shell environment variable
def numToEnvVariables(num):
    if num:
        env_file = os.getenv('GITHUB_ENV')
        with open(env_file, "a") as myfile:
            myfile.write(('IssueID' + "=" + num + "\n"))

def get_issue_title():
    return str(sys.argv[2])

if __name__ == '__main__':
    headers = {
    'Authorization': f"Bearer " + sys.argv[1],
    'Accept': 'application/vnd.github.v3+json',
    }
    http_poll()

```

Thanks Ajay

**Comment by achin16** [comment]
It is fixed after renaming the file name. thank you.
