### ISSUE TITLE
Doesn't account for 'no route to host' errors

### ISSUE THREAD

**Issue by BarryNorton** [justiniso/polling#3]
This is essential for polling on, e.g., new EC2 instances.

```
Traceback (most recent call last):
  File "./test.py", line [...]
    poll_forever=True
  File "/usr/local/lib/python2.7/dist-packages/polling.py", line 103, in poll
    val = target(*args, **kwargs)
  File "./launch.py", line 39, in <lambda>
    lambda: requests.get([...]).status_code == 200,
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool([...]): Max retries exceeded with url: / (Caused by <class 'socket.error'>: [Errno 113] No route to host)
```

**Comment by justiniso** [comment]
Hey @BarryNorton I'm not sure I understand the issue. What behavior would you expect when you get this error?

You can ignore the exception if you want to keep polling:

```python
polling.poll(
    lambda: requests.get('<your_host>').status_code == 200,
    ...
    ignore_exceptions=(requests.exceptions.ConnectionError,),
    poll_forever=True)
```

Or you can write your own polling function:

```python
def can_connect():
    try:
        requests.get('<your_host>').status_code == 200
    except requests.exceptions.ConnectionError:
        return False

polling.poll(
    can_connect,
    ...
    poll_forever=True)
```

Happy to support other use cases, I'm just not sure I understand what the intended behavior is.

**Comment by BarryNorton** [comment]
Yes, this is what I did in the end.

You're right no extra polling behaviour is needed for this but, especially given it's so useful for EC2, it might be worth expanding the requests-based example in the documentation (?)

**Comment by justiniso** [comment]
Sure, I've updated the readme to include this example.
